[project]
name = "gcode-generator"
version = "0.9.0"
description = "Generates g-code files to calibrate 3D printers and inks for direct ink writing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.11.24",
    "matplotlib>=3.10.1",
]
